// Mandatory basic health insurance (OKP) premiums by commune.
//
// Data: lib/data/health-premiums.json, generated by
// scripts/build-health-premiums.py from FOPH's annual premium publication.
// FOPH publishes premiums once a year as static files, so they are imported
// rather than fetched at runtime. See that script for the averaging method.

import data from './data/health-premiums.json'

type AgeClass = 'child' | 'youngAdult' | 'adult'

interface RegionPremiums {
  child: number
  youngAdult: number
  adult: number
  insurers: Record<AgeClass, number>
}

const REGIONS = data.regions as Record<string, RegionPremiums>
const COMMUNES = data.communes as Record<string, string>

export const PREMIUM_YEAR: number = data.premiumYear

export interface Household {
  /** Aged 26 and over */
  adults: number
  /** Aged 19–25 */
  youngAdults: number
  /** Aged 0–18 */
  children: number
}

export interface HealthPremiumEstimate {
  premiumYear: number
  canton: string
  premiumRegion: number
  /** Regional average monthly premium per person, CHF */
  perPerson: Record<AgeClass, number>
  monthlyTotal: number
  annualTotal: number
  method: string
  source: string
}

const round2 = (n: number) => Math.round(n * 100) / 100

/** Returns null when the BFS number is not a commune in the premium year. */
export function estimateHealthPremiums(bfsNumber: number, household: Household): HealthPremiumEstimate | null {
  const regionKey = COMMUNES[String(bfsNumber)]
  if (!regionKey) return null
  const region = REGIONS[regionKey]
  const [canton, premiumRegion] = regionKey.split('-')

  const monthlyTotal = round2(
    household.adults * region.adult +
    household.youngAdults * region.youngAdult +
    household.children * region.child
  )

  return {
    premiumYear: PREMIUM_YEAR,
    canton,
    premiumRegion: Number(premiumRegion),
    perPerson: { child: region.child, youngAdult: region.youngAdult, adult: region.adult },
    monthlyTotal,
    annualTotal: round2(monthlyTotal * 12),
    method: data.method,
    source: data.source,
  }
}
